# # 
# name: Unit tests on Dev Account

# on:
#   workflow_dispatch:
#   # push:
#   #   branches:
#   #     - main
#   # pull_request:
#   #   types:
#   #     - opened
#   #   branches:
#   #     - 'main/**'
#   schedule:
#     - cron: '41 3 * * *' # runs nightly at 3:41 am
# env:
#   AWS_REGION : "eu-north-1"
# # Permission can be added at job level or workflow level    
# permissions:
#       id-token: write   # This is required for requesting the JWT
#       contents: read    # This is required for actions/checkout
# jobs:
#   WholeWorkFlow:
#     runs-on: self-hosted
#     steps:
#       - name: Git clone the repository
#         uses: actions/checkout@v4
#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.8' 
#       - name: configure aws credentials
#         uses: aws-actions/configure-aws-credentials@v1.7.0
#         with:
#           role-to-assume: ${{ secrets.UT_ROLE_NAME }}
#           role-session-name: GitHub_to_AWS_via_FederatedOIDC
#           aws-region: ${{ env.AWS_REGION }}
#       - name: Sts GetCallerIdentity
#         run: |
#           aws sts get-caller-identity     
#       - name: Set up Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: '1.21.3'      
#         # Install the latest version of Terraform CLI
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#             terraform_wrapper: false

#   # Get all golang dependencies
#       - name: Get dependencies
#         working-directory: ./infrastructure/test/unittests
#         run: go mod tidy
#   # Run tests
#       - name: Run unittests
#         id: unit-tests
#         working-directory: ./infrastructure/test/unittests
#         run: go test -v -timeout 90m | tee summary.txt

#       - name: Slack Notification
#         uses: rtCamp/action-slack-notify@v2
#         if: steps.unit-tests.outputs.exitcode == 2
#         env:
#           SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
#           SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#           SLACK_ICON: https://github.com/github.png?size=460
#           SLACK_MESSAGE: '$(cat summary.txt) :rocket:'
#           SLACK_TITLE: Unit tests failing
#           SLACK_USERNAME: GithubActionSlackBot
#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}